### ISSUE TITLE
Update French Language Support

### ISSUE THREAD

**Issue by MichelRahme** [MichelRahme/ConcordiaNavigation#79]
Currently only menu items support both languages

Acceptance Criteria:
 - [ ] Support french language in search bar.
 - [ ] Support french language in the calendar page.
 - [ ] Support french language in the shuttle schedule page.
